### ISSUE TITLE
Boss tsulong

### ISSUE THREAD

**Issue by davidwow1024** [davidwow1024/alpha5.4.8#18]
https://www.wowhead.com/npc=62442/tsulong
 Acá lo bug es en la segunda fase la de día que el boss hay que curarlo mientras el va soltando bichos que van a venir a pegarle, los jugadores tienen que matar esos bichos antes que le peguen y como se están moviendo no se les pude pegar sale el mismo problema de fuera de alcance

**Comment by Syrus23** [comment]
Cuando tenga un chance testee esto para confirmar.
@davidwow1024
