### ISSUE TITLE
mazmorras del torneo argenta 

### ISSUE THREAD

**Issue by davidwow1024** [davidwow1024/alpha5.4.8#22]
https://www.wowhead.com/wotlk/es/zone=4723/prueba-del-campe%C3%B3n
 ambas mazmorras necesitan cariño

**Comment by Syrus23** [comment]
Corregidos los detalles que se encontraron tanto en 'Trial of the Crusader' como en 'Trial of the Champion', necesita testeo para confirmar estado actual.

@davidwow1024
