### ISSUE TITLE
Asedio de orgrimmar!

### ISSUE THREAD

**Issue by davidwow1024** [davidwow1024/alpha5.4.8#24]
https://es.wowhead.com/siege-of-orgrimmar

https://es.wowhead.com/npc=71543/immerseus

Las babosas que salen en la sala, tienes que pegarte a ellas para poder darle golpe sino no puedes
https://www.wowhead.com/spell=143309
el boss se queda estático y no visualmente no gira por lo que se hace imposible esquivarlo

https://es.wowhead.com/npc=71734/sha-del-orgullo

Llega un momento de la pelea que paraliza a los jugadores y los demas tienen que liberar a los paralizados, ahi es donde todo se rompe, 
despues que mueres y hasta que wipeas cuando revives el personaje se queda paralizado en el piso sin poder hacer ninguna accion

https://es.wowhead.com/npc=72249/galakras

El problema de este boss es que los cañones cuando los disaras deben stunear al boss por un rato prolongado  y entonces dispararle una segunda vez cuando ya esta 
stuneado y ahi es cuando cae el boss y se le puede pegar todo deberia suceder con un solo cañon. Esta mecánica se repite 2 veces para poder matarlo
Primero liberas la primera torre y derribas al boss con 2 cañonazos y cuando baja se le pega hasta que este en 50% de vida y el vuelve a volar, entonces en ese momento
vas a la 2da torre haces la misma operacion hasta que mueres
Al no poder darle 2 veces con el mismo cañon nosotros utilizamos las 2 torres para poder tumbarlo y el boss se reinicio a mitad del evento porque ya las 2 torres habian sido utilizadas
el efecto de stuneo del cañon deberia ser un poco mas prolongado para que se le pueda dar 2 veces con un mismo cañon

**Comment by Syrus23** [comment]
@davidwow1024 Immerseus - SpellId: 143309 Swirl/Remolino, arreglado... necesita testeo para confirmar

> https://es.wowhead.com/siege-of-orgrimmar
> 
> https://es.wowhead.com/npc=71543/immerseus
> 
> Las babosas que salen en la sala, tienes que pegarte a ellas para poder darle golpe sino no puedes https://www.wowhead.com/spell=143309 el boss se queda estático y no visualmente no gira por lo que se hace imposible esquivarlo
> 
> https://es.wowhead.com/npc=71734/sha-del-orgullo
> 
> Llega un momento de la pelea que paraliza a los jugadores y los demas tienen que liberar a los paralizados, ahi es donde todo se rompe, despues que mueres y hasta que wipeas cuando revives el personaje se queda paralizado en el piso sin poder hacer ninguna accion
> 
> https://es.wowhead.com/npc=72249/galakras
> 
> El problema de este boss es que los cañones cuando los disaras deben stunear al boss por un rato prolongado y entonces dispararle una segunda vez cuando ya esta stuneado y ahi es cuando cae el boss y se le puede pegar todo deberia suceder con un solo cañon. Esta mecánica se repite 2 veces para poder matarlo Primero liberas la primera torre y derribas al boss con 2 cañonazos y cuando baja se le pega hasta que este en 50% de vida y el vuelve a volar, entonces en ese momento vas a la 2da torre haces la misma operacion hasta que mueres Al no poder darle 2 veces con el mismo cañon nosotros utilizamos las 2 torres para poder tumbarlo y el boss se reinicio a mitad del evento porque ya las 2 torres habian sido utilizadas el efecto de stuneo del cañon deberia ser un poco mas prolongado para que se le pueda dar 2 veces con un mismo cañon

@davidwow1024 Immerseus - SpellId: [143309 Swirl/Remolino](https://www.wowhead.com/spell=143309), arreglado... necesita testeo para confirmar

**Comment by Syrus23** [comment]
Immerseus - SpellId: [143309 (Swirl/Remolino)](https://www.wowhead.com/spell=143309), reparado... necesita testeo para confirmar.

@davidwow1024

**Comment by Syrus23** [comment]
Sha of Pride - [Evento: Corrupted Prison](https://youtu.be/VWJkss8SJ9Q?t=149).
Arreglado bug que al morir los jugadores en la prisión no podían moverse ni realizar ninguna acción. Necesita testeo para confirmar.

@davidwow1024

**Comment by davidwow1024** [comment]
https://es.wowhead.com/npc=71543/immerseus corregido problema de no girar con la spell 
@Syrus23

**Comment by davidwow1024** [comment]
https://www.youtube.com/watch?v=4AaXCbYIcG4 funciona bien mal descripcion en el reporte mecanica en video
