### ISSUE TITLE
Quest "El Tanto de la Victoria" 

### ISSUE THREAD

**Issue by Lifakgarcia** [davidwow1024/alpha5.4.8#29]
Quest "El Tanto de la Victoria" ID_Quest:24503
ID_Quest_QStarter: 37106
Esta autocompletable deberia poder marcar un golpe y ver como alamuerte baja ... 

tendria que funcionar asi :
https://youtu.be/-hJbL8SBtTU

**Comment by davidwow1024** [comment]
fixed
