### ISSUE TITLE
Derio vestusto no se puede leer

### ISSUE THREAD

**Issue by Gamerkun48** [davidwow1024/alpha5.4.8#30]
https://www.wowhead.com/es/item=103977/diario-vetusto aqui se muestra la informacion que se deberia saber de cada Mob de la isla temporal y tesoros, sirve para evitrarte una muerte por no saber las habilides especiales de los mobs

**Comment by davidwow1024** [comment]
Man lo que dices es q ese ítem no da los detalles para ló que sirve o es la descripción de el ??

**Comment by Gamerkun48** [comment]
no se puede ver el contenido del libro

**Comment by mariodanny91** [comment]
Esta en ingles aqui, seria traducirlo . O_O tiene 27 paginas.
https://mop-shoot.tauri.hu/?item=103977

**Comment by davidwow1024** [comment]
Fixed
