### ISSUE TITLE
serpiente de la selva 

### ISSUE THREAD

**Issue by Gamerkun48** [davidwow1024/alpha5.4.8#43]
https://www.wowhead.com/es/npc=52224/serpiente-de-la-selva#english-comments
no tiene ni vida ni daño ni nivel que deberia 
ya que sirve para una mision nivel 35

**Comment by davidwow1024** [comment]
http://mop-shoot.tauri.hu/?quest=29103 segun una base de datos de mop esta bien ya que por wowhead se ve de otro nivel por la expancion que lleva
