### ISSUE TITLE
Esencia de eranikus

### ISSUE THREAD

**Issue by Gamerkun48** [davidwow1024/alpha5.4.8#44]
https://www.wowhead.com/classic/es/npc=5709/sombra-de-eranikus
Despues de matar a jamma´l y los dracos verdes deberia activarse en forma de combate para meterle unos ptazos

**Comment by Syrus23** [comment]
Corregido, luego de matar los 3 bosses anteriores a este al entrar a la sala el boss ya está de pie para iniciar el evento.

**Comment by Syrus23** [comment]
Corregido, luego de matar los 3 bosses anteriores a este al entrar a la sala el boss ya está de pie para iniciar el evento.
