### ISSUE TITLE
Espiritu de fuego de jade

### ISSUE THREAD

**Issue by Gamerkun48** [davidwow1024/alpha5.4.8#49]
https://www.wowhead.com/es/npc=72769/espíritu-de-fuego-de-jade
su habilidad [Golpe de llama de jade](https://www.wowhead.com/es/spell=147456/golpe-de-llama-de-jade) no respeta los 2 metros para hacer el daño aunque estes mas lejos te da.

**Comment by Syrus23** [comment]
Testear de nuevo para comprobar, el alcance del spell son de 20y que son aprox 18m, 2.25m es el radio que afecta al rededor del punto de impacto.
@davidwow1024 @Gamerkun48
