### ISSUE TITLE
Piroguardia brasadivino

### ISSUE THREAD

**Issue by Gamerkun48** [davidwow1024/alpha5.4.8#50]
https://www.wowhead.com/classic/es/npc=9816/piroguardián-brasadivino
No se activa con su ritual por lo tanto no crece y no se puede asesinar, cuando esta sin activar te puede pegar y matar, pero no le puedes hacer nada, aparte el no deberia moverse mientras no se haga el ritual .

**Comment by Syrus23** [comment]
Corregido, después de que todos los integrantes del grupo toquen el altar la duración total del evento hasta que empieza a atacar es de 32s.
