### ISSUE TITLE
quest : Llorando a moco tendido

### ISSUE THREAD

**Issue by remamakiller** [davidwow1024/alpha5.4.8#53]
esta quest https://www.wowhead.com/es/quest=29765/llorando-a-moco-tendido , tienes que matar unos npc que dropeen los items , que pide la quest

item=74160/rifle-de-zinjun 
item=74161/ojo-izquierdo-de-zinjun
item=74162/ojo-derecho-de-zinjun
item=74163/cadáver-de-snuff
Es muy bajo el porcentaje de suerte y no dropea

**Comment by remamakiller** [comment]
Fix

UPDATE `creature_loot_template` SET `ChanceOrQuestChance`='13' WHERE `item`='74160';
UPDATE `creature_loot_template` SET `ChanceOrQuestChance`='13' WHERE `item`='74161';
UPDATE `creature_loot_template` SET `ChanceOrQuestChance`='13' WHERE `item`='74162';
UPDATE `creature_loot_template` SET `ChanceOrQuestChance`='13' WHERE `item`='74163';

**Comment by davidwow1024** [comment]
Fixed Thanks @remamakiller
