### ISSUE TITLE
quest Monstruosidad

### ISSUE THREAD

**Issue by remamakiller** [davidwow1024/alpha5.4.8#56]
En esta quest , https://www.wowhead.com/quest=29743/monstrosity
hay que interactuar , con el npc , que abre un dialogo , para tocar y completar la quest
No lo hace y no se completa
Asi tiene que ser , pero al tocarlo , no hace nada
https://youtu.be/BNgOOAJ5MK8

**Comment by Syrus23** [comment]
Subido arreglo, necesita testeo para confirmar.

**Comment by davidwow1024** [comment]
Fixed
