### ISSUE TITLE
quest  Masacre en la Punta de la Luz

### ISSUE THREAD

**Issue by remamakiller** [davidwow1024/alpha5.4.8#57]
En esta quest , https://www.wowhead.com/wotlk/es/quest=12701/masacre-en-la-punta-de-la-luz
cuando te subes al cañon ,  los soldados te atacan y te matan , se ve que el rate.creature aggro  que tiene , para atacarte , es de muy lejos
Si logras completar  , cuando tocas el icono de  " Escape de grifo esquelectico " , para que te lleve a entregar , volando
Se va hacia lo profundo del mar y te mata la fatiga
Se puede completar yendo a caballo , pero para eso está ese icono , que te lleva volando
y no lo hace

**Comment by davidwow1024** [comment]
fixed
