### ISSUE TITLE
quest Siguiendo el rastro: múrlocs

### ISSUE THREAD

**Issue by remamakiller** [davidwow1024/alpha5.4.8#59]
en esta quest https://www.wowhead.com/es/quest=26214/siguiendo-el-rastro-m%C3%BArlocs
al matar el Murloc , tiene que lotear el item 57756 , pero está demaciado bajo el drop
Tiene que quedar así  , dejo fix
update `creature_loot_template` set `ChanceOrQuestChance`= '-50' where `item` = 57756;

**Comment by Ironzide** [comment]
@davidwow1024 @Syrus23 Ya este se puede cerrar.

**Comment by davidwow1024** [comment]
Fixed
