### ISSUE TITLE
quest  [Las palabras de despedida de Lou]

### ISSUE THREAD

**Issue by remamakiller** [davidwow1024/alpha5.4.8#60]
En esta Quest   https://www.wowhead.com/es/quest=26232/las-palabras-de-despedida-de-lou
Hay que espiar a los matones , que ellos te vengan a atacar , matar a los 4 matones y te
completa la quest
No lo hace , los matas y no pasa nada
Así debe de trabajar , esta quest
https://www.youtube.com/watch?v=0TUcutXBWSE&t=1s

**Comment by davidwow1024** [comment]
fixed
