### ISSUE TITLE
Quest En defensa de los Páramos de Poniente

### ISSUE THREAD

**Issue by remamakiller** [davidwow1024/alpha5.4.8#61]
En esta quest  https://www.wowhead.com/es/quest=26286/en-defensa-de-los-p%C3%A1ramos-de-poniente
El moob Tosco Zarparrío , no dropea el item 58111 : https://www.wowhead.com/es/item=58111/%C3%B3rdenes-de-ataque-gnoll
Y no se completa la quest

**Comment by davidwow1024** [comment]
fixed
