### ISSUE TITLE
En busca del padre es practicamente autocompletable.

### ISSUE THREAD

**Issue by Gamerkun48** [davidwow1024/alpha5.4.8#70]
https://www.wowhead.com/es/quest=30933/en-busca-del-padre
Esta mision es autocompletable ya que en todo momento el padre esta atras de la niña,que deberia estar alli despues de entregar la mision y el centinela yukao que esta en donde debe estar en las fosas de agape no se le puede hablar, solo esta alli de adorno.

**Comment by davidwow1024** [comment]
en testeo

**Comment by davidwow1024** [comment]
fixed
